common: &common
  adapter: postgresql
  username: flashcards

development:
  <<: *common
  database: flashcards_development

test: &test
  <<: *common
  database: flashcards_test

production:
  <<: *common
  database: flashcards_production

cucumber:
  <<: *test